---
- hosts: all
  connection: local
  name: Get system inventory
  gather_facts: False

  tasks:
  - name: Get system inventory
    dellemc_get_system_inventory:
       idrac_ip:   "{{ inventory_hostname }}"
       idrac_user: "{{ user_idrac }}"
       idrac_pwd:  "{{ pwd_idrac }}"
